### ISSUE TITLE
Make "cd \" available to switch to root

### ISSUE THREAD

**Issue by SchlenkR** [ChrisPritchard/FSH#16]
On Windows, it's common to use "cd \" or "cd\" to switch to the current drive's root. In FSH, only "cd /" works.

**Comment by ChrisPritchard** [comment]
@ronaldschlenker Not super sure what you mean. I use windows and "cd" by itself does nothing in either powershell or cmd. Can you give me some more detail?

**Comment by ChrisPritchard** [comment]
In case its some specific windows thing I use Windows 10 Pro, English (NZ).

**Comment by ChrisPritchard** [comment]
Nevermind, I figured out what you are saying. You need to use \\\\ in markdown comments for a \\. I will see about fixing this, cheers

**Comment by ChrisPritchard** [comment]
Resolved in commit 0f1f59e

**Comment by SchlenkR** [comment]
Exactly! Backslash :) cheers!
