### ISSUE TITLE
No release links which mentioned on the README.md

### ISSUE THREAD

**Issue by Neftedollar** [ChrisPritchard/FSH#18]
**Additionally, there are precompiled releases available. These were pre-built using dotnet publish for win-x64, linux-x64 and osx-x64, and should run without needing the framework installed. Access these from the releases link.**

But there is no release links

**Comment by ChrisPritchard** [comment]
My bad. I removed the releases because they fell behind rapid bug fixes. I'll probably create more releases once the applied f# competition is over and the code grows more stable.

**Comment by ChrisPritchard** [comment]
Thanks for the notice. Resolved in commit 78939e2
