### ISSUE TITLE
Parenthesis in strings are counted on the bracket stack

### ISSUE THREAD

**Issue by ChrisPritchard** [ChrisPritchard/FSH#2]
This command does not work properly: (let s = "1x5)BC")

Not sure what should be done about this: maybe count " in the bracket push algorithm?

**Comment by voronoipotato** [comment]
when a quote starts everything after it isn't responded to until there's another quote, I would think. I'm going to familiarize myself with this and see what's up.

**Comment by ChrisPritchard** [comment]
I'll probably have to rewrite the parser to solve this properly, I think. Which is probably ok, since I think the parser is a bit dense anyway.

**Comment by ChrisPritchard** [comment]
Resolved in commit c95d8bbad76705adf9746a9556a00780b2956dde. Didn't rewrite the parser, just made it even _more_ dense
