### ISSUE TITLE
Support for home folder

### ISSUE THREAD

**Issue by nojaf** [ChrisPritchard/FSH#21]
Hello, I gave this project a test run on Windows.
It would be great if `cd ~` worked as well.

I'm guessing it would require a small change in https://github.com/ChrisPritchard/FSH/blob/master/src/Builtins.fs#L46 right?
Replace any `~` with `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)`

Would you accept a PR?

**Comment by ChrisPritchard** [comment]
Sure! Though to be honest I haven't looked at this for a year. I need to bump it to net core 3, and retest on osx/linux to see if it fixes the tty performance and formatting issues.

If you PR, just note I probably won't respond for half a day due to timezone differences :)
