### ISSUE TITLE
dotnet tool

### ISSUE THREAD

**Issue by jkone27** [ChrisPritchard/FSH#25]
can this be available as a global dotnet tool ?

https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools

**Comment by ChrisPritchard** [comment]
Ill take a look

**Comment by ChrisPritchard** [comment]
This has been setup, and its also been updated to .NET 6.0. The nuget package will be at https://www.nuget.org/packages/FSH, though of course you can still build and install locally 👍

**Comment by jkone27** [comment]
awesome!  :)  will give it a spin
