### ISSUE TITLE
Support loading RC files

### ISSUE THREAD

**Issue by ChrisPritchard** [ChrisPritchard/FSH#7]
A .rc file, a run command file, is a file that is loaded and run on startup. FSH could support these for loading precommands: e.g., you could define 'grep' as (fun args -> ...) then this would be compiled and interpreted as possibly a built-in on load

**Comment by ChrisPritchard** [comment]
I'm not going to do this any time soon. Closing for now.

**Comment by voronoipotato** [comment]
I would think the init.rc file could also have all your FSH config settings as well. Think of it like the init.el in emacs. You should use the github project board to track feature ideas like this.

**Comment by ChrisPritchard** [comment]
@voronoipotato It would be a nice feature. But I think the current issues with Unix systems have to take priority. Though that said, its looking like my unix issues are problems with dotnet core's console implementation rather than FSH code so...
