### ISSUE TITLE
Add pre-compiled releases for various platforms

### ISSUE THREAD

**Issue by ChrisPritchard** [ChrisPritchard/FSH#9]
This might make it easier to use FSH, if users don't need to have .net core installed and build expertise in order to get going. On the other hand, the project is a bit educational re F#/dotnet core... so... but better to be egalitarian anyway.

**Comment by voronoipotato** [comment]
Is this talking about `dotnet publish --self-contained`? I think it's not a bad idea if we can get this to not even require dotnet core as a dependency, at least as an option.

**Comment by ChrisPritchard** [comment]
Completed

**Comment by ChrisPritchard** [comment]
The new release fell behind the bug fixes pretty quickly, so I deleted it. I think I'll add a release if/when it gets more stable.

**Comment by voronoipotato** [comment]
Sounds good
